### ISSUE TITLE
binary search algorithm

### ISSUE THREAD

**Issue by Dipendra982** [Dipendra982/learningC#3]
implement a program in C to find if a number is present in a sorted array using the binary search algorithm?

**Comment by Visnusah** [comment]
```c
#include <stdio.h>

// Function to perform binary search
int binarySearch(int arr[], int n, int target) {
    int left = 0;
    int right = n - 1;

    while (left <= right) {
        int mid = left + (right - left) / 2;

        // If the target is found at mid, return its index
        if (arr[mid] == target)
            return mid;

        // If the target is greater than the middle element, ignore the left half
        if (arr[mid] < target)
            left = mid + 1;
        // If the target is smaller than the middle element, ignore the right half
        else
            right = mid - 1;
    }

    // If the target is not found in the array, return -1
    return -1;
}

int main() {
    int arr[] = {2, 5, 8, 12, 16, 23, 38, 56, 72, 91};
    int n = sizeof(arr) / sizeof(arr[0]);
    int target = 23; // Number to search for

    int result = binarySearch(arr, n, target);

    if (result != -1)
        printf("Element found at index %d\n", result);
    else
        printf("Element not found in the array\n");

    return 0;
}

``` 


**In this solution, we define a binarySearch function that takes a sorted array (arr), its size (n), and the target number (target) to search for.
Inside the binarySearch function, we initialize two pointers, left and right, to define the search interval.
We repeatedly divide the search interval in half and update the pointers based on whether the target is greater or smaller than the middle element.
If the target is found at any point during the search, we return its index. If the target is not found, we return -1.
In the main function, we define an example sorted array arr, specify the target number target, and call the binarySearch function to search for the target in the array.
Finally, we print whether the target element was found in the array or not.**

**Comment by Dipendra982** [comment]
Thanks!
